export const COHORTS = [
  {
    cohortId: 'NEET_Dropper',
    name: 'NEET Dropper',
    version: 1,
    description: 'Students who dropped a year to prepare for NEET',
    pitchPoints: [
      'Structured dropper batch with dedicated faculty',
      'Daily mock tests aligned with NEET pattern',
      'Previous year toppers mentorship program',
    ],
    commonObjections: ['high_fees', 'already_tried_coaching', 'online_is_enough', 'need_to_think'],
    personas: ['student', 'father', 'mother'],
    difficultyPresets: {
      knowledge: 3,
      emotion: 2,
      budget: 4,
      timePressure: 3,
      competitorLoyalty: 3,
      decisionAuthority: 4,
    },
    targetSkills: ['neet_specific', 'dropper_handling', 'scholarship', 'pricing', 'parent_engagement'],
    isActive: false,
  },
  {
    cohortId: 'NEET_Dropper',
    name: 'NEET Dropper',
    version: 2,
    description: 'Updated NEET dropper pitch with enhanced scholarship program',
    pitchPoints: [
      'New 40% scholarship for dropper batch enrollments',
      'AI-powered personalized study plans',
      'Guaranteed rank improvement or fee refund',
      'Weekend parent progress reports',
    ],
    commonObjections: ['high_fees', 'scholarship_not_enough', 'competitor_cheaper', 'need_parent_approval'],
    personas: ['student', 'father', 'mother'],
    difficultyPresets: {
      knowledge: 3,
      emotion: 3,
      budget: 5,
      timePressure: 4,
      competitorLoyalty: 4,
      decisionAuthority: 5,
    },
    targetSkills: ['neet_specific', 'dropper_handling', 'scholarship', 'pricing', 'scholarship_negotiation'],
    isActive: true,
  },
  {
    cohortId: 'JEE_Foundation',
    name: 'JEE Foundation',
    version: 1,
    description: 'Class 11-12 students targeting JEE Main and Advanced',
    pitchPoints: [
      'IIT alumni faculty network',
      'Integrated school + coaching model',
      'Olympiad preparation included',
    ],
    commonObjections: ['too_early', 'school_workload', 'high_fees', 'distance'],
    personas: ['student', 'father', 'mother'],
    difficultyPresets: {
      knowledge: 4,
      emotion: 2,
      budget: 4,
      timePressure: 3,
      competitorLoyalty: 3,
      decisionAuthority: 4,
    },
    targetSkills: ['jee_specific', 'academic_knowledge', 'faculty', 'pricing'],
    isActive: true,
  },
];

export const KNOWLEDGE_NODES = [
  {
    nodeId: 'neet_v2_obj_high_fees',
    type: 'objection',
    label: 'High Fees',
    content: 'The fees are too high for our budget. We cannot afford this.',
    cohortId: 'NEET_Dropper',
    cohortVersion: 2,
    tags: ['pricing', 'budget'],
    relatedSkills: ['pricing', 'price_objection', 'scholarship'],
  },
  {
    nodeId: 'neet_v2_counter_scholarship',
    type: 'counter',
    label: 'Scholarship Counter',
    content: 'We offer up to 40% scholarship based on your previous NEET score and a scholarship test.',
    cohortId: 'NEET_Dropper',
    cohortVersion: 2,
    tags: ['scholarship', 'pricing'],
    relatedSkills: ['scholarship', 'scholarship_negotiation'],
  },
  {
    nodeId: 'neet_v2_pitch_scholarship',
    type: 'pitch',
    label: 'Scholarship Pitch',
    content: 'Our new dropper batch includes a 40% scholarship program — the best in the market for repeaters.',
    cohortId: 'NEET_Dropper',
    cohortVersion: 2,
    tags: ['scholarship'],
    relatedSkills: ['scholarship', 'value_proposition'],
  },
  {
    nodeId: 'neet_v2_obj_competitor',
    type: 'objection',
    label: 'Competitor Cheaper',
    content: 'Other coaching centers are offering the same thing at half the price.',
    cohortId: 'NEET_Dropper',
    cohortVersion: 2,
    tags: ['competitor', 'pricing'],
    relatedSkills: ['competitor_comparison', 'competitor_objection', 'value_proposition'],
  },
  {
    nodeId: 'neet_v2_counter_rank_improvement',
    type: 'counter',
    label: 'Rank Improvement Guarantee',
    content: 'We guarantee rank improvement or fee refund — no other institute offers this for droppers.',
    cohortId: 'NEET_Dropper',
    cohortVersion: 2,
    tags: ['value', 'guarantee'],
    relatedSkills: ['value_proposition', 'social_proof'],
  },
  {
    nodeId: 'neet_v2_intent_pricing',
    type: 'intent',
    label: 'Pricing Inquiry',
    content: 'Parent wants to understand total cost including hostel and materials.',
    cohortId: 'NEET_Dropper',
    cohortVersion: 2,
    tags: ['pricing'],
    relatedSkills: ['pricing', 'emi_plans'],
  },
  {
    nodeId: 'neet_v2_question_scholarship',
    type: 'question',
    label: 'Scholarship Eligibility',
    content: 'What score do I need to get the maximum scholarship?',
    cohortId: 'NEET_Dropper',
    cohortVersion: 2,
    tags: ['scholarship'],
    relatedSkills: ['scholarship', 'scholarship_negotiation'],
  },
  {
    nodeId: 'neet_v2_emotion_anxious',
    type: 'emotion',
    label: 'Academic Anxiety',
    content: 'Parent is worried child will waste another year if coaching fails again.',
    cohortId: 'NEET_Dropper',
    cohortVersion: 2,
    tags: ['emotion', 'anxiety'],
    relatedSkills: ['empathy', 'dropper_handling', 'trust_building'],
  },
];

export const KNOWLEDGE_EDGES = [
  {
    fromNodeId: 'neet_v2_obj_high_fees',
    toNodeId: 'neet_v2_counter_scholarship',
    relationship: 'responds_to',
    cohortId: 'NEET_Dropper',
    cohortVersion: 2,
  },
  {
    fromNodeId: 'neet_v2_obj_high_fees',
    toNodeId: 'neet_v2_pitch_scholarship',
    relationship: 'leads_to',
    cohortId: 'NEET_Dropper',
    cohortVersion: 2,
  },
  {
    fromNodeId: 'neet_v2_obj_competitor',
    toNodeId: 'neet_v2_counter_rank_improvement',
    relationship: 'responds_to',
    cohortId: 'NEET_Dropper',
    cohortVersion: 2,
  },
  {
    fromNodeId: 'neet_v2_intent_pricing',
    toNodeId: 'neet_v2_question_scholarship',
    relationship: 'leads_to',
    cohortId: 'NEET_Dropper',
    cohortVersion: 2,
  },
];
